# Generated by Django 5.0.3 on 2024-03-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='capital_required_for_univerisy',
            new_name='capital_required_for_university',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='credit_card_outstanding',
        ),
    ]
