# Generated by Django 5.0.3 on 2024-03-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_existingpolicies_life_insurance_property_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liabilitydetails',
            old_name='total_liabilities',
            new_name='totalLiabilities',
        ),
    ]
