# Generated by Django 5.0.3 on 2024-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_total_liabilities_liabilitydetails_totalliabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedetails',
            name='income_from_property',
        ),
        migrations.AddField(
            model_name='incomedetails',
            name='propertyInome',
            field=models.CharField(blank=True, null=True),
        ),
    ]
