# Generated by Django 5.0.3 on 2024-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_incomedetails_income_from_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedetails',
            name='propertyInome',
        ),
        migrations.AddField(
            model_name='incomedetails',
            name='propertyIncome',
            field=models.CharField(blank=True, null=True),
        ),
    ]
