# Generated by Django 5.0.3 on 2024-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_incomedetails_propertyinome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedetails',
            name='interest',
        ),
        migrations.AddField(
            model_name='incomedetails',
            name='Interest',
            field=models.CharField(blank=True, null=True),
        ),
    ]
