# Generated by Django 5.0.3 on 2024-03-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_existingpolicies_life_insurance_property_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='contact_number',
            new_name='phoneNumber',
        ),
    ]
