# Generated by Django 5.0.3 on 2024-03-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_contact_number_personaldetails_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='phoneNumber',
            field=models.CharField(blank=True),
        ),
    ]
